name: Java CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Generate random cache key to ensure the cach directories are saved after build
        # see https://github.com/actions/cache/issues/432#issuecomment-740376179
      id: random-cache-key
      run: head /dev/random -c 32 > random-cache-key
    - name: Setup caching directories for local Maven repo and for DB of successfuly built hashversioned modules
      uses: actions/cache@v2
      with:
        path: |
          ~/.m2/repository
          ~/successful-hashvers
        key: ${{ runner.os }}-maven-${{ hashFiles('random-cache-key') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Determine affected Maven projects
      id: affected-projects
      shell: bash
      run: |
        find "${HOME}/successful-hashvers" || true # print the dir content, for troubleshooting
        mkdir -p "${HOME}/successful-hashvers" || true
        mvn pro.avodonosov:hashver-maven-plugin:1.6:projects-to-build -DdbDir="${HOME}/successful-hashvers"
        echo "::set-output name=list::$(cat target/hashver-projects-to-build)"
    - name: Build the affected Maven projects
      if: ${{ steps.affected-projects.outputs.list }}
      run: mvn -B verify -pl ${{ steps.affected-projects.outputs.list }} -am
    - name: Save successfull hashvers
      if: ${{ steps.affected-projects.outputs.list && success() }}
      run: |
        cp -r target/hashver-db-additions/* "${HOME}/successful-hashvers"
        find "${HOME}/successful-hashvers" || true # print the dir content, for troubleshooting
